// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed/seed.ts",
  },
  datasource: {
    // Prisma CLI operations (migrate, db seed, studio) need a direct connection —
    // Neon's pooled connection doesn't support the advisory locks Migrate uses.
    // Falls back to DATABASE_URL for local dev, which is already a direct connection.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
